#!/usr/bin/env python3
"""
servo_jitter.py - find out WHY the servo shakes.

Put the car on a box so the front wheels hang free, motor off, and WATCH AND
LISTEN to the steering while this runs. It holds ONE CONSTANT ANGLE three
different ways for six seconds each, announcing every change.

The command never changes during a phase. So anything that moves is NOT the
control loop, the wall readings, or the smoothing - it is how the pulse is
being generated, or the servo itself.

    A  RPi.GPIO, pulse HELD          <- what open_challenge.py does now
    B  RPi.GPIO, pulse RELEASED      <- what their original code did
    C  pigpio, DMA-timed pulse       <- hardware timing, needs pigpiod

What the result means:

    shakes in A and B, still in C   -> software PWM jitter. RPi.GPIO times the
                                       pulse from a Python thread, so every
                                       scheduling hiccup moves the pulse edge.
                                       Fix: drive the servo with pigpio.
    still in B, shakes in A         -> the servo is HUNTING against its own
                                       feedback while powered. Fix: go back to
                                       releasing the pulse (SERVO_HOLD=False).
    shakes in all three             -> not the signal. Look at the linkage,
                                       the servo itself, or the power rail.

Nothing but the steering moves. The motor pins are never touched.
"""
import sys
import os
import time

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
import open_challenge as OPEN          # noqa: E402  for the pin and the trim

PIN = OPEN.SERVO_PIN
TRIM = OPEN.SERVO_TRIM
ANGLE = float(sys.argv[1]) if len(sys.argv) > 1 else 0.0
HOLD_S = float(sys.argv[2]) if len(sys.argv) > 2 else 6.0

target = 90.0 + ANGLE + TRIM
duty = 2.5 + (target / 180.0) * 10.0
pulse_us = 1000.0 + (target / 180.0) * 1000.0     # 1000-2000 us over 0-180

print()
print("=" * 66)
print("  SERVO JITTER TEST   pin GPIO%d   angle %+.1f (trim %+.1f -> %.1f deg)"
      % (PIN, ANGLE, TRIM, target))
print("  WATCH THE STEERING. The command never changes inside a phase.")
print("=" * 66)


def phase(name, why):
    print()
    print("  --- %s ---" % name)
    print("      %s" % why)


import RPi.GPIO as GPIO
GPIO.setmode(GPIO.BCM)
GPIO.setwarnings(False)
GPIO.setup(PIN, GPIO.OUT)
pwm = GPIO.PWM(PIN, 50)
pwm.start(0)

phase("A  RPi.GPIO, pulse HELD  (what open_challenge.py does now)",
      "duty written once, then left running for %.0f s" % HOLD_S)
pwm.ChangeDutyCycle(duty)
time.sleep(HOLD_S)

phase("B  RPi.GPIO, pulse RELEASED  (what their original code did)",
      "duty written, then set to 0 so the servo goes limp - repeated at 10 Hz")
t0 = time.time()
while time.time() - t0 < HOLD_S:
    pwm.ChangeDutyCycle(duty)
    time.sleep(0.1)
    pwm.ChangeDutyCycle(0)
    time.sleep(0.0)
pwm.ChangeDutyCycle(0)
pwm.stop()
GPIO.cleanup(PIN)
time.sleep(0.4)

phase("C  pigpio, DMA-timed pulse  (hardware timing)",
      "pulse width %.0f us, generated by DMA instead of a Python thread"
      % pulse_us)
ok = False
try:
    import pigpio
    pi = pigpio.pi()
    if not pi.connected:
        print("      pigpiod IS NOT RUNNING. Start it with:")
        print("          sudo pigpiod")
        print("      then run this again to see phase C.")
    else:
        pi.set_servo_pulsewidth(PIN, pulse_us)
        time.sleep(HOLD_S)
        pi.set_servo_pulsewidth(PIN, 0)
        pi.stop()
        ok = True
except ImportError:
    print("      pigpio module not installed - skipping phase C")

print()
print("=" * 66)
if ok:
    print("  Which phase was STILL?")
    print("    C still, A and B shaky  -> software PWM jitter. Switch the servo")
    print("                               to pigpio.")
    print("    B still, A shaky        -> the servo hunts while powered. Set")
    print("                               SERVO_HOLD = False.")
    print("    all three shaky         -> not the signal. Linkage, servo or")
    print("                               the power rail.")
else:
    print("  Phase C did not run, so software-PWM jitter is still untested.")
print("=" * 66)
